### ISSUE TITLE
No em-, en-,... Spaces

### ISSUE THREAD

**Issue by netzego** [scribusproject/scribus#102]
Probably something is missing in my build, and in the packages form my distro. I'am not able to insert spaces.

I'am reading in a post, Scribus only using characters which are in the font. And indeed, with some fonts, it's possible to insert those spaces. On the other hand, on my osx, i'am also can do this with any font. So what the heck of library do i miss?

**Comment by aoloe** [comment]
you need the em and en spaces in your font to work.

please ask for support on http://forums.scribus.net or on the mailing list (http://lists.scribus.net/mailman/listinfo/scribus).

this issues tracker is for bugs and feature requests...
(and it's not even t he official bug tracker for scribus...)
