### ISSUE TITLE
Story editor should support "undo"

### ISSUE THREAD

**Issue by wzab** [scribusproject/scribus#105]
A few times it happened to me, that after a longer edition I have made a stupid mistake and e.g. deleted a huge part of the text. Currently there is no way to undo it. I can only leave the story editor without updating the text frame.
Of course, I can press CTRL+U before each risky operation, but it is very easy to forget about it.
Undo is a standard function in most text editors. Why it is not available in Scribus story editor?

**Comment by aoloe** [comment]
i don't think that such a change will be made in the current story editor.

you should not use the story editor for larger edits...

- load your content from office / text files or
- edit your text in the frame.

**Comment by aoloe** [comment]
(... the story editor is End of Life... and needs a rewrite...)
