### ISSUE TITLE
Since the IDML import works, how about a Python wrapper for it?

### ISSUE THREAD

**Issue by cd-rum** [scribusproject/scribus#112]
I desperately want to be able to import IDML/IDMS files through Python. How hard would it be to write a wrapper around the plugin to provide basic importing?

**Comment by cd-rum** [comment]
Nevermind, `placeSVG` works for .idms files.

**Comment by aoloe** [comment]
i guess that `placeSVG` might need to be renamed then...

i've opened a ticket in the official bug tracker

https://bugs.scribus.net/view.php?id=15609

and for your question: it's rather easy to add new commands to the scripter, it just takes some time to grok how other did the same thing in the past and then tweak the right files.

it's mostly copy paste and you can look at older commits to see what is needed...
