### ISSUE TITLE
Get picture... context menu item greyed out until Ctrl+I to invoke

### ISSUE THREAD

**Issue by kingwarrick** [scribusproject/scribus#114]
Scribus Version 1.5.4 appimage on Debian 9.

Not sure how reproducible this is, because I can't reproduce it now, but it was definitely happening and definitely not intended behaviour.

Fresh download of Scribus, first time for this machine. Created a new file with text and image boxes. Right clicked on an image box to get a picture, and the right-click menu item was greyed out. Same thing through the regular menu.

Ctrl+I brought up the image selection box, and ever since then, I am able to right click and Get picture..
Correct behaviour on new files as well, seems to be working now since the Ctrl+I.

Not sure if anyone else has run in to this, and not sure how much use I can be in making it happen again.

**Comment by aoloe** [comment]
i've never seen that... all we can do is leave the ticket open and seen if it also happens for other people...

**Comment by JLuc** [comment]
It happened to me when i downloaded and installed appimage (on Ubuntu 18.04). All menus were greyed out. I didnt find the CTRL+I trick to get a normal scribus so i forgot about using latest appimage to test lastest bug fixes.
