### ISSUE TITLE
Any way to set bleed from Python?

### ISSUE THREAD

**Issue by cd-rum** [scribusproject/scribus#121]
Really struggling on this one.

**Comment by aoloe** [comment]
there is a ticket in the official scribus bug tracker for it

https://bugs.scribus.net/view.php?id=15493

and it has a patch in there...

i'll ping jean and see if the patch has any issue or if it can be accepted...

**Comment by sonejostudios** [comment]
yes, please, this method is really missing!

**Comment by cd-rum** [comment]
@sonejostudios I've written a workaround for this which involves closing the file and editing the XML directly. Might help before a patch is out.
    
    from xml.etree import ElementTree as et
    
    scribus.saveDocAs(sla_path)
    scribus.closeDoc()
    BLEED = '14.1732283464567'
    tree = et.parse(sla_path)
    xml = tree.find('DOCUMENT')
    xml.set('BleedTop', BLEED)
    xml.set('BleedBottom', BLEED)
    xml.set('BleedLeft', BLEED)
    xml.set('BleedRight', BLEED)
    tree.write(sla_path)
    scribus.openDoc(sla_path)

**Comment by sonejostudios** [comment]
this is great, thanks!

**Comment by aoloe** [comment]
If somebody wants to implement this and needs help, just ask...
It's not that hard : - )

**Comment by aoloe** [comment]
the patch has been accepted: https://bugs.scribus.net/view.php?id=15493
