### ISSUE TITLE
AppImage 1.5.5 Segmentation fault (x86)

### ISSUE THREAD

**Issue by Andres6936** [scribusproject/scribus#131]
I had the AppImage installed some time ago, but when I used it again I found the following error:

```shellsession
andres6936@Tierra ~/Scribus $ ./Scribus-1.5.5-linux-x86_64.AppImage 
Run experimental bundle that bundles everything
QApplication: invalid style override passed, ignoring it.
Fontconfig warning: FcPattern object weight does not accept value [80 205)
Segmentation fault
```

**Comment by aoloe** [comment]
there is not much information...

but:

 -from the warning before the crash
- and the fact that it worked in the past

it might be a font issue.

would you mind trying the daily appimage from the gitlab CI.

did you add a new font to your system?

**Comment by Andres6936** [comment]
> did you add a new font to your system?

Yes, I have installed three fonts since then, but I also removed the development headers from Qt5, I really don't have much certainty about what could have produced such an error.

**Comment by Andres6936** [comment]
I executed the following command: `fc-cache -f -v`, and tried again to open the AppImage, however it still has the same error mentioned.

**Comment by aoloe** [comment]
removing the -dev files won't have any effect on an appimage.

have you try to remove the three fonts you added?

you could also  try https://gitlab.com/scribus/scribus/-/jobs/artifacts/master/raw/Scribus-nightly-x86_64.AppImage?job=appimage%3Alinux to see if there is a bug that has already been fixed.

**Comment by Andres6936** [comment]
I'm gonna try this one: https://gitlab.com/scribus/scribus/-/jobs/582550241/artifacts/download?file_type=archive

If it doesn't work, I'll try the AppImage you proposed.

**Comment by Andres6936** [comment]
I tried it again with the latest GitLab CI AppImage

```shellsession
andres6936@Tierra ~/Scribus $ ./Scribus-nightly-x86_64.AppImage 
Run experimental bundle that bundles everything
QApplication: invalid style override passed, ignoring it.
    Available styles: gtk2, Windows, Fusion
Fontconfig warning: FcPattern object weight does not accept value [80 205)
Segmentation fault
```

**Comment by aoloe** [comment]
what you tried at first was already the latest... my link is just the "general" link to the latest job : - )

i would say that you should try to

- move all fonts out of ~/.fonts
- rename ~./config/scribus
- launch scribus with new configs and see it works

if it works, than it's up to you if you want to restore the old config and track down the issue or use the new configs and restart configuring your scribus.

if it does not work... mmm... it will work.

**Comment by Andres6936** [comment]
1. Move all fonts out of ~/.fonts not work (because not exist the directory)
2. Remove ~./config/scribus not work.

**Comment by Andres6936** [comment]
Another thing to comment on, download Scribus 1.4.4 from the `apt-get` and it works.

**Comment by aoloe** [comment]
If 1.4.4. works then it's again a bit more likely that the issue is on the "Appimage  side".  
But 1.4.4 does not suport otf fonts, so the fonts might still be an issue.

If you have an old version of your distribution, it's possible that Scribus requires a newer version of a library that is not packaged in the Appimage.  
Depending on how old the other Appimage was, this is possible or not...  
Which distribution and version?

If you're on Ubuntu, you could try if there is a PPA for your version (if there is not , then it's unlikely that the Appimage will work on your system; other distributions might have similar ways for distributing newer packages).

**Comment by Andres6936** [comment]
> Which distribution and version?

**Operating System**: Linux Mint 18.2 Cinnamon 64-bit

**Comment by Andres6936** [comment]
The problem is much worse, out of the question, I installed an application from the Snap shop and when I went to run the installed application I found the same error, apparently the problem is with my system and not with Scribus or the AppImage.

**Comment by Andres6936** [comment]
If I fixed it, Scribus 1.5.5 and the other applications already work, what I have done is the following:

- I searched the last fonts installed on the system with the font-manager utility and found that among the installed fonts was Font-Awesome. My suspicions were mainly focused on this one, due to its nature.
- Remove the font with the sudo rm command ...
- Reload the font cache

Everything's back to normal.

**Comment by aoloe** [comment]
@Andres6936 can you post the link to the place where you did download your font?

btw, i don't know much about mint, but you should not have had to remove the font with "sudo rm".

basically, you should install and uninstall fonts with your package manager OR  the fontmanager OR add (and remove them) without sudo.

**Comment by Andres6936** [comment]
I honestly don't know how Font Awesome was installed on the system and the other fonts I downloaded from Google Font (Here is one that I installed and removed: https://fonts.google.com/specimen/Luckiest+Guy?query=luck).

> you should not have had to remove the font with "sudo rm"

I saw this in a tutorial of how to remove fonts in Ubuntu (Mint is based on Ubuntu), also the fonts installed were made from Fontmanager but for some strange reason I don't let myself remove them (even running it with sudo), so I had to use sudo rm and then fc-cache.
