### ISSUE TITLE
colouring grouped objects

### ISSUE THREAD

**Issue by Rik44444** [scribusproject/scribus#136]
hello all,
i'm a new user to Scribus and just want to say: amazing job!! Really well done, amazing what can be done with it.
1 suggestion for improvement: i tried to change the colour of a set of grouped objects, and discovered that I had to ungroup them first, before i could do this. Would be handy if you could change the colour for all objects at once in a group. 
PS: I see this IS possible when selecting multiple objects at once, so also making it possible for grouped objects appears feasible

**Comment by aoloe** [comment]
as far as i know, scribus does not yet support applying formatting to multiple items at once.

there are a few cases where the features are not disabled and setting the color seems to be one of them.
setting the line width is also activated, and it works correctly.

as far as i know, the biggest issue is about what to show in the palettes.
some programs show the values grayed out.
that's probably the best solution.
in the case of the lines scribus is simply showing the value for the first item and applies the value to all items as soon as the value changes.

implementing the change at this point is possible but implies modifying most of the dialogs in scribus.
a bigger task that i don't think will be done before 1.6 is out.

**Comment by aoloe** [comment]
i've opened a ticket in the official scribus bug tracker and i will close this ticket, since yours is a long term wish that does not need to be tracked here...

https://bugs.scribus.net/view.php?id=16173

thanks for caring!
a.l.e
