### ISSUE TITLE
[appimage 1.5.6.1] Scribus 'Print Separation' issues.

### ISSUE THREAD

**Issue by abhidesh128** [scribusproject/scribus#140]
I am currently working on a document for pre-press. 

In print dialogue of Scribus, on the option tab, we can print a document normally, or with color separation. When 'Print Separation' is selected, we can select which color is to be separated. There are four options - All, Cyan, Magenta, Yellow. But there is no Black option. So, I can't separate individual black color. Why is black not included ?

Also, when I select 'All' option, Scribus prints a color separated postscript file, that has Black, Cyan and Magenta separations, but no Yellow separation.

Why is Scribus not printing all colors separations even when I select 'All' option ? Is it a bug ?

`Scribus Version : 1.5.6.1 - SVN Version: 24251`
`Build ID: C--T-F-C1.15.10-64bit`
`Using Ghostscript version 9.27`

**Comment by aoloe** [comment]
hi

welcome to scribus.

please ask for support in <https://forums.scribus.net>.

in my eyes, it's unlikely that you're facing a bug, but if it's the case, please open a ticket in the offiical bug tracker: <https://bugs.scribus.net>

i close this ticket and let you use one of the official scribus channel.

**Comment by abhidesh128** [comment]
@aoloe Thank you for your response. I will post on forum.
