### ISSUE TITLE
Annotation link Y-pos resets

### ISSUE THREAD

**Issue by erik-sk** [scribusproject/scribus#141]
When entering position for page links with the Link Annotation too, I find that the Y-pos changes from the number entered to some other number  (not sure what it is based on). Editing the link annotation a second time will result in the desired position.
In the screenshots below, you can see that it has reset to 246 pt. Other times it resets to other points on the page. The X-pos works as expected.

![2021-04-07_12-45](https://user-images.githubusercontent.com/37672001/113807617-6f6de780-979f-11eb-93d5-d1c20754cdf2.png)
![2021-04-07_12-45_1](https://user-images.githubusercontent.com/37672001/113807628-739a0500-979f-11eb-9a43-03a538706819.png)

**Comment by aoloe** [comment]
can you please post a ticket to <https://bugs.scribus.net>?

btw, i seem to recall that a similar ticket has been already filled there...

**Comment by erik-sk** [comment]
After checking bug tracker, found issue #[0016497](https://bugs.scribus.net/view.php?id=16497) is identical to the problem am having, and is labeled as closed and fixed in version 1.5.7. I'll close this here for now and wait to see if it is resolved when the update comes out. Thanks.
