### ISSUE TITLE
Adding XeLaTeX Support

### ISSUE THREAD

**Issue by abhidesh128** [scribusproject/scribus#142]
Scribus has support for LaTeX which is very helpful for rendering mathematical expression. But it's limitation is we can't directly use OpenType Unicode fonts. I have written a editorconfig file in order to get XeLaTeX support.

Could it be useful in current implementation ? I am sharing the file in attachment.

[600_xelatex.txt](https://github.com/scribusproject/scribus/files/6271065/600_xelatex.txt)

**Comment by zzzazzz** [comment]
Hi, you should try this place instead
https://bugs.scribus.net

**Comment by abhidesh128** [comment]
@zzzazzz Thank you for your response. I have reported this to Scribus bug tracker.

Closing this issue, Thanks again..!
