### ISSUE TITLE
Implement PDF export via command line execution

### ISSUE THREAD

**Issue by supersexy** [scribusproject/scribus#144]
I need to convert scribus documents to pdf files - as this is a tool well known in the Linux world I was absolutely sure that developers _of course_ were thinking about such a great possibility for automation! BUT what an unbelievable downfall, what a deep takedown ripped my soul when I realized that _they actually did not_ - WHAT? 

How can anybody not see the automation power that Scribus could bring to open source printing? 

What an _obvious_ thing to do to make Scribus a _premium pandoc_ with a perfect gui for setting up templates.

I can not understand the lack of vision here. I was so sure that from the first moment of course Scribus was designed as a tool that could be used in a classical unix pipeline workflow to mass-produce pretty things. 

Please do it. Thanks.

If it already exists - or any other tool that can convert scribus files to pdf, please make me happy again.

**Comment by aoloe** [comment]
hi

scribus is a UI for creating print ready PDFs.

other tools exist for creating PDFs from the command line.

and you can use scripting in scribus (and partially from the shell) to mass-produce PDFs from scribus documents.
it's not perfect for the task, but you can get it to work. and people already did that.

please use https://forums.scribus.net for discussing your ideas. this is an issue tracker, not a discussion forum : - )
