### ISSUE TITLE
Implement printing via command line execution

### ISSUE THREAD

**Issue by supersexy** [scribusproject/scribus#145]
Please let me print scribus files from the command line. I need the GUI only for the design phase, but I want to be able to quickly print things from the command line or via an API. 

I really still hope that this is just a documentation bug and that _of course_ you have implemented such a great thing. 

I mean you program a tool like scribus and you never got the idea that printing could be automated? I can not believe that.

**Comment by aoloe** [comment]
i'm pretty sure you can do that with a small script (and some piping).

this is not an official bug tracker for scribus and it's (sadly) meaningless leaving this type general feature requests open.  
please use https://bugs.scribus.net and/or https://forums.scribus.net

closing...
