### ISSUE TITLE
Implement templates and variables like report generator

### ISSUE THREAD

**Issue by supersexy** [scribusproject/scribus#146]
I see that [Scribusgenerator](http://www.ekkehardwill.de/sg/) exists, but I want a very basic thing like templates to be implemented and supported in the main code base. Yes, Scribus of course should be used as a very good report creation tool that is easy to connect with all kinds of external data sources like files, databases, directories with files, whatever.

**Comment by aoloe** [comment]
scribus does have templates.

scribus generator some gaps.

i've created an experimental  / basic clone of it that fully runs inside scribus.  
i can further work on it if there is interest. but, right now, i will only do that for money or in coordination with a well thought proejct with clear goals and a bright future.

this is the third rant you have filled....
i see that you are slowly discovering that you can do things with scribus...
even if it's not perfect  : - )
