### ISSUE TITLE
Color change when vector image is imported

### ISSUE THREAD

**Issue by computerartclub** [scribusproject/scribus#147]
Scribus: 1.5.7
Expected behavior: Vector will import with same colors present in the Inkscape SVG file
Experienced behavior: the image, which has less than 5 colors, shifts some orange objects into brown.

Temporary fix: 
    Click into edit -> replace colors
    Find the color in question.
    Replace the brown with the correct orange.

If this is an expected behavior, perhaps Scribus has detected that it is outside a certain printing range, could we get a message warning about this instead of shifting the color unexpectedly?

**Comment by aoloe** [comment]
can you please open a ticket on https://bugs.scribus.net and attach there:

- a sample svg file
- the resulting pdf produced by scribus

thanks!
a.l.e
