### ISSUE TITLE
Crowdsourced translations via Transifex

### ISSUE THREAD

**Issue by luzpaz** [scribusproject/scribus#15]
## Moved this issue to https://github.com/scribusproject/scribus-translations/issues/1
~~Official Scribus Transifex Translation Repo~~
- [x] Automating transfer from Transifex => SVN
     [patch](http://bugs.scribus.net/view.php?id=13097) submitted by @chhitz to streamline downloading Transifex translations.  
- [ ] @chhitz help
- [x] Announce Transifex to Scribus List. [link](http://lists.scribus.net/pipermail/scribus/2015-June/052022.html)
- [ ] Assign Coordinators and Reviewers for each language **IN PROCESS** 
   * Progress shown [here](https://www.transifex.com/projects/p/scribus)
- [ ] Create introductory manual/FAQ for Translators [Translating Scribus](https://github.com/scribusproject/scribus/wiki/Translating-Scribus)
   - [x] 2 Ways to Translate [DONE](https://github.com/scribusproject/scribus/wiki/Translating-Scribus#howto-translate-scribus)
   - [ ] Translating vs Reviewing [TODO]
   - [ ] Discussing issues via the scribus forum [TODO] + [URL]
- [x] Close zdpo's repo and transfer any diff'ed translations to the new repo

--------
### Reference URLs
* Transifex [translation jargon](http://docs.transifex.com/developer/formats/)
* [Transifex](http://bugs.scribus.net/view.php?id=10589) in Scribus issue queue
* [Scribus in Transifex](https://www.transifex.com/projects/p/Scribus)
* Scribus translation files in [Trunk](https://github.com/scribusproject/scribus/tree/master/resources/translations)
* Scribus [translators](https://github.com/scribusproject/scribus/blob/master/TRANSLATION)  
* Now obsolete Scribus Transifex issue [now closed](https://github.com/scribusproject/scribus/issues/7)

**Comment by luzpaz** [comment]
@chhitz Hey mate, not sure you're back yet. But when you are...can you help me figure out how to diff translations from [old scribus transifex](https://www.transifex.com/projects/p/Scribus_140/) to new [transifex](https://www.transifex.com/projects/p/Scribus).

**Comment by luzpaz** [comment]
@chhitz so what happens if translators submit translations and we update the resource .ts file ? Do the translations need to be re-entered ?

**Comment by luzpaz** [comment]
Adding Screengrabs for tutorial

**Comment by chhitz** [comment]
imported the translations from the zdpo repo into the new Transifex. diffs here: https://github.com/scribusproject/scribus-translations/commit/7b61331edb1080215d01feecba65b400334a6594

**Comment by luzpaz** [comment]
Make sure that translators don't add unnecessary newlines 
![remove-newlines](https://cloud.githubusercontent.com/assets/4140247/8778877/e05af634-2ec5-11e5-9b68-488f4b640e3e.gif)

**Comment by luzpaz** [comment]
Closing this in favor of https://github.com/scribusproject/scribus-translations/issues/1
