### ISSUE TITLE
Can't see the pdf action buttons on mac (faded into color of container)

### ISSUE THREAD

**Issue by alita-moore** [scribusproject/scribus#150]
![Screen Shot 2021-10-08 at 7 19 47 PM](https://user-images.githubusercontent.com/26529820/136636940-6dad6fa7-7278-4a8e-9cf2-dc541f6877c7.png)

**Comment by ryandesign** [comment]
This looks like [this bug](https://bugs.scribus.net/view.php?id=15969) with the solution given in [this comment](https://bugs.scribus.net/view.php?id=15969#c49185): go to the Scribus menu, choose Preferences..., select User Interface from the list on the left, go to Icon Set and manually choose a dark icon set.
