### ISSUE TITLE
Scribus 1.5.7 build fails with Qt 6.2

### ISSUE THREAD

**Issue by rezso** [scribusproject/scribus#151]
In file included from scribus/third_party/zip/scribus_zip.cpp:25:
scribus/util.h: In function ‘QString getUniqueName(const QString&, const STRINGLIST&)’:
scribus/util.h:179:9: error: ‘QRegExp’ does not name a type
  179 |  static QRegExp rx("^(.*)\\s+\\((\\d+)\\)$");

**Comment by aoloe** [comment]
should work "now"
