### ISSUE TITLE
Suggestion: Guidelines, margin outline, bleed lines should always be on the top layer.

### ISSUE THREAD

**Issue by rickqinj** [scribusproject/scribus#153]
Thank you to the team for this splendid software!
So far I am using Scribus 1.4.8 win10 to design my flyer.
And just one suggestion here. Can we fix those assistant lines (guideline, margin outline, bleed lines, etc.) always on the top layer? I just found that the image box, that lays on the first layer with the **blend mode** `normal`, will cover those assistant lines if they are overlapped.

**Comment by aoloe** [comment]
hi @rickqinj this is already in 1.5.x (and has been there for ages : - )

or am i missing something?

**Comment by rickqinj** [comment]
> hi @rickqinj this is already in 1.5.x (and has been there for ages : - )
> 
> or am i missing something?

Great! I cannot wait any longer to try the latest version. You guys are really amazing!
