### ISSUE TITLE
[ Feature request ] multi page resources support?

### ISSUE THREAD

**Issue by AlvesR0** [scribusproject/scribus#154]
Hello. If it's a duplicate. forgive me. because I didn't find a topic dealing with it.Is there a possibility of multi-page support in Scribus in a future release?

Thanks in advance.
AlvesRO.

**Comment by aoloe** [comment]
hi alves,

can you please ask this question in the [forums](https://forums.scribus.net)?

this is a non official bug tracker not a support site : - )

you will probably need to specify what kind of resources you want to use.
as an example, multi page PDFs can already be included  in a scribus document.

ciao
a.l.e
