### ISSUE TITLE
Scribus appimage file are included "additional data" from PPA ?

### ISSUE THREAD

**Issue by Augusto7743** [scribusproject/scribus#155]
I not see how have a information support about Scribus thus I have created a issue.

In link below
https://wiki.scribus.net/canvas/Debian
have details about "Additional data, color profiles, templates, and auxiliary applications" being installed when using distro ubuntu apt-get scribus from PPA.

In Scribus appimage include all additional data above ( scribus-template , icc-profiles , lprof and podofo ) ?
If not is included if installing using PPA deb files works with appimage release ?
Thanks for reply.

**Comment by aoloe** [comment]
no, the additional data and files are probably not included in the appimage.

if you install the resources through PPA or deb files they should be available to the appimage. but i have not tested.

for support, please use https://forums.scribus.net : - )

**Comment by Augusto7743** [comment]
Thanks for the forums links.
That information need to be added in scribus web site.
