### ISSUE TITLE
implement printing via cups api

### ISSUE THREAD

**Issue by abma** [scribusproject/scribus#156]
currently scribus just calls lpr for printing which requires i.e. "cups-bsd" on debian to be installed. it would be nice if cups would be directly used:

https://www.cups.org/doc/cupspm.html#submitting-a-print-job

i guess some generic class for printing would be nice as there is duplicate code for printing already:

https://github.com/scribusproject/scribus/search?q=lpr

**Comment by aoloe** [comment]
as i already wrote, i'm not sure that printing with cups is a good idea.

but if you want scribus to better support it, i guess you should add a ticket to https://bugs.scribus.net , the official scribus bug tracker.
