### ISSUE TITLE
Convert pdf to sla via command line

### ISSUE THREAD

**Issue by etho201** [scribusproject/scribus#158]
Is it possible to use Scribus command line scripts to convert a single `.pdf` file into a Scribus `.sla` file?

Basically, I want to do the opposite of:

```bash
scribus -g -py to-pdf.py file.sla
```

**Comment by etho201** [comment]
I almost have this working, using the following:

Create a file named `to-sla.py` with the following contents:
```python
import os, scribus

if scribus.haveDoc() :
    filename = os.path.splitext(scribus.getDocName())[0]
    scribus.saveDocAs(filename+".sla")
else :
    print("No file open")
```

Now run:

```bash
scribus -g -py to-sla.py file.pdf
```

This will open Scribus and will save the file as an `.sla` file, but the only gotcha is the `PDF-Import` window appears first and you have to hit "enter" to select to import `All pages`.

I'd like to make this completely non-interactive. Is there a way to automatically import all pages?

**Comment by aoloe** [comment]
hi, this is not a support forum : - )

please consider posting this type of questions in https://forums.scribus.net or stackoverflow...

i will give you a short reply and then close this ticket...

---

you can simply open a pdf with scribus and save it as .sla (and modify it before saving it).

i did not test, but i'm pretty sure you can do that from a script, too...

also, i'm not sure if the scripter offers the option to import the text as such... if it's not the case, please consider making a feature request on https://bugs.scribus.net
