### ISSUE TITLE
swear words in German GUI 1.5.8

### ISSUE THREAD

**Issue by webman2030** [scribusproject/scribus#160]
![image](https://user-images.githubusercontent.com/29649132/176194440-e5cee9b9-e91a-4523-ac9b-c4791e5b970d.png)

Hurenkinder = whore children

**Comment by webman2030** [comment]
these terms date from 1900, and are offensive

Quote Wiki: (https://de.wikipedia.org/wiki/Hurenkind_und_Schusterjunge)
Die Desktop-Publishing-Software (DTP) übernimmt diese Aufgaben, die meist verwendete Bezeichnung für das Hurenkind- und Schusterjungenproblem ist **_Absatzkontrolle_**. Diese wird von den meisten Layoutprogrammen und Textverarbeitungen als Standard angeboten.

**Comment by aoloe** [comment]
hi @webman2030 

you're welcome to suggest in https://bugs.scribus.net that the title of the section should be changed in _Absatzkontrolle_. I think it's a meaningful proposal.

there is an active maintainer for the german translation, so i would not try to make a pull request, but ask for the change and see how that person reacts.

I'll close this thread here and hope that you'll post your request in the official bug tracker.
