### ISSUE TITLE
Snap to Guides ignored when Snap to Grid is on

### ISSUE THREAD

**Issue by virtualritz** [scribusproject/scribus#166]
I'm using Scribus 1.5.8 (release from official Ubuntu 22.04 repo.).

I can only get my objects (textboxes, shapes etc.) to snap to my guides when **Page/Snap to Grid** is *off*.

When both **Page/Snap to Guides** and **Page/Snap to Grid** are *on*, guide-snapping is not working.
My grid is spaced @ 100mm/10mm.

**Comment by aoloe** [comment]
Late answer.

Indeed with 10cm / 1cm, I can get items to move to a guide but not resize them to it.

Personally, I don't see much of interest on having both the grid and the guides active at the same time (well, I would say that in most cases it's not a good idea to use the grid in Scribus... but that's another topic...), but if you still care about this bug, please report it to https://bugs.scribus.net .
(this is just a community mirror of the official Scribus code)

**Comment by virtualritz** [comment]
Nah, I switched to typst a while ago. It's at the stage where you can do DTP with it. Beers!
