### ISSUE TITLE
Doesn't build with podofo 0.10.0

### ISSUE THREAD

**Issue by risicle** [scribusproject/scribus#169]
Hi,

Just letting you know that podofo 0.10.0 has some API-breaking changes and scribus doesn't currently build with it. This would normally not be particularly important but podofo 0.9.x has some open CVEs on it that look like they're not going to get backports to the 0.9 branch. Some more helpful porting information: https://github.com/podofo/podofo/wiki/PoDoFo-API-migration-guide

**Comment by aoloe** [comment]
this ticket has also been filled in the scribus issue tracker

https://bugs.scribus.net/view.php?id=16948

thanks for reporting the issue!
