### ISSUE TITLE
unable to align images within the bounding box

### ISSUE THREAD

**Issue by morgajel** [scribusproject/scribus#17]
suppose you have a 4 inch square image that you want to center over a double-column text area. If the image were text, you'd be able to stretch the bounding box to the margins and align to the center of the box.

It would be nice if Images could do this as well.

**Comment by morgajel** [comment]
http://bugs.scribus.net/view.php?id=11649

already exists in the mantis tracker, I just couldn't find it.

**Comment by aoloe** [comment]
http://bugs.scribus.net/view.php?id=11649
