### ISSUE TITLE
Python API: Recurse into groups

### ISSUE THREAD

**Issue by wnavarre** [scribusproject/scribus#171]
I am having the same issue as described on the forum here: https://forums.scribus.net/index.php/topic,4469.msg20519.html#msg20519

I want to be able to recurse into groups using the Python API in order to examine the text frames and image frames within. 

I cannot find any documented way to achieve this.

**Comment by aoloe** [comment]
please ask the question in the forums (or fill a ticket in the official issue tracker https://bugs.scribus.net)

**Comment by aoloe** [comment]
no feedback.
