### ISSUE TITLE
Import of Inkscape pages

### ISSUE THREAD

**Issue by datalot-369** [scribusproject/scribus#172]
## Background

First time mentioned in https://chat.inkscape.org/channel/team_devel?msg=iF8P2nx8v8e7t4tz2

> Yesterday, I was approaching the Pages Tool for a Business Card creation, so I had to convert everything to paths and so to make CMYK colors in Scribus...
> 
> The problem: Scribus doesn'nt recognize Inkscape pages.
> 
> Is there a way to make this possible or is up to Scribus to do this?
> 
> By the way, an Scribus project can't be saved as .svg so I think this could only be unidirectional.

So doctormo, the creator of the Pages Tool at Inkscape replied:

>  It's entirely up to scribus, and our pages format isn't a standard (yet) although I did a talk at penpotfest about this kind of cross-software editable-svg standard.

## Details

Inkscape 1.2.0 introduced the Pages Tool, a new tool able to create and manage pages inside the SVG file format. This is an Inkscape-specific feature that allows us to organize our work and export to PDF format in ways never seen before.

It would be a game-changer if we could only open the .svg file in Scribus and all pages got recognized automatically, so we can proceed with the conversion of color and finally exporting to a multipage PDF seamlessly.

**Comment by aoloe** [comment]
hi

this is jsut a mirror of the scribus svn repository.

would you mind filling a copy of this ticket in https://bugs.scribus.net ?

**Comment by datalot-369** [comment]
Done. https://bugs.scribus.net/view.php?id=17009
