### ISSUE TITLE
"Copy item properties" doesn't work without the "Tools" panel

### ISSUE THREAD

**Issue by danielkrajnik** [scribusproject/scribus#175]
I've assigned a shortcut (ctrl shift alt c) to "Copy item properties" and it works when the tools panel is visible, but it stops working when it's disabled. It would be good if it worked regardless of the tools panel.

![image](https://github.com/scribusproject/scribus/assets/15096799/c80f2705-b8ea-4a28-8be4-3523d4aeef3b)

**Comment by aoloe** [comment]
hi daniel

this is only a mirror of the official scribus repository

you're welcome to post a ticket in the official bug tracker: https://bugs.scribus.net

ciao
a.l.e

**Comment by danielkrajnik** [comment]
Thank you for letting me know. I'll post it there.

**Comment by danielkrajnik** [comment]
@aoloe I'm keep getting an error when trying to sign up: `Your account may be disabled or blocked or the username/password you entered is incorrect.`

**Comment by aoloe** [comment]
hi @danielkrajnik 

sorry for the inconvenience.

sadly, the bug tracker is one of the few scribus system where i have the least access rights and i cannot check on users.

but you can use https://bugs.scribus.net/lost_pwd_page.php to get your password re-initialized.

**Comment by danielkrajnik** [comment]
Thanks, I've tried it, tried shorter passwords, real names and different email domains, but it kept failing:

```
APPLICATION ERROR #2800
Invalid form security token. This could be caused by a session timeout, or accidentally submitting the form twice.
``` 

I've email the site administrator, hopefully they will reply soon.
