### ISSUE TITLE
Left align last line of paragraph when the whole paragraph is set to justify

### ISSUE THREAD

**Issue by ignutanz** [scribusproject/scribus#180]
It is seen that when the force justify alignment is set for a paragraph, the last line spaces could be large to fit the line to both ends. This should not happen. The last line should be left aligned

**Comment by aoloe** [comment]
Am I missing something?

The only difference between the _simple_ and the _forced_ justification seems to be the way the last line is justified...

What are you trying to achieve, that can't be done by simply justifying your text?

**Comment by ignutanz** [comment]
Sorry, I didnt know that i could do it using just the "Align Text Justified". I had only seen the force justify. Closing the issue
