### ISSUE TITLE
(temporary fix Scribus 1.6.2 on macOS Sequoia Version 15.0) "Scribus.app" is damaged and can't be opened. You should move it to the Trash. This file was downloaded on an unknown date.

### ISSUE THREAD

**Issue by flagsoft** [scribusproject/scribus#186]
### "Scribus.app" is damaged and can't be opened. 

Scribus.app version used:
https://sourceforge.net/projects/scribus/files/scribus/1.6.2/

Direct link to scribus-1.6.2.dmg
https://sourceforge.net/projects/scribus/files/scribus/1.6.2/scribus-1.6.2.dmg/download

After installing **macOS Sequoia Version 15.0 (24A335)** I got this error:

```"Scribus.app" is damaged and can't be opened. You should move it to the Trash. This file was downloaded on an unknown date. [Cancel] [Move to Trash]```

<img width="260" alt="scribus-01" src="https://github.com/user-attachments/assets/c79282da-7aab-4bf2-b7d8-604543df4d85">

### Temporary Solution

1. Go to **Settings** > **Privacy & Security**. Then scroll down to **section Security**, click "**Open Anyway**".

<img width="701" alt="scribus-02" src="https://github.com/user-attachments/assets/7ab8f2d4-3f56-4642-b193-5f3a0663d0f3">

```"Scribus.app" was blocked to protect your Mac.  [Open Anyway]```
```Apple could not verify "Scribus.app" is free of malware that may harm your Mac or compromise your privacy.```

3. Just start Scribus as usual. Should start right away.

### What triggered this issue? 
Unknown so far.

### Source
**Safely open apps on your Mac**
https://support.apple.com/en-us/102445

**Comment by aoloe** [comment]
And which steps would improve the situation for you?

I guess that this happens for any software you download from somewhere else than Apple's own shop...

**Comment by flagsoft** [comment]
> And which steps would improve the situation for you?
> 
> I guess that this happens for any software you download from somewhere else than Apple's own shop...

No, of course not, this does not happened before macOS Sequoia Version 15.0. Not on macOS Sonoma, etc.

**This happens only on macOS Sequoia Version 15.0 for Scribus.**

**Comment by aoloe** [comment]
if you're sure that this does not depend on your system, can you please post a ticket in https://bugs.scribus.net ?

with the details about the Os version where Scribus works and does not work.

as the description says, this repository is only a mirror of the official one and the devs are not following the tickets submitted in here.
