### ISSUE TITLE
scribus.net links (bugtracker and others) are not working on the github page because of missing https://

### ISSUE THREAD

**Issue by Josvanegmond** [scribusproject/scribus#187]
[bugs.scribus.net](http://bugs.scribus.net) on the github about and in the description below under contributing are not working. Took me a bit to figure out it's missing http**s**:// . This is the case for all links.  

![image](https://github.com/user-attachments/assets/d256fe2b-2a57-4764-95db-7bba48c915bf)

**Comment by aoloe** [comment]
thanks!

i've fixed the links and simplified a bit the description.
