### ISSUE TITLE
Currens SVN revision 20332 does not compile

### ISSUE THREAD

**Issue by LiamHD** [scribusproject/scribus#21]
I just tried to compile the current SVN head on my macbook.
I used homebrew for this.
Compile brings up this message:
/tmp/scribus20150816-63208-1iq715k/scribus/plugins/barcodegenerator/barcodegenerator.cpp:756:11: error: no matching function for call to 'callGS'
        int gs = callGS(gargs,NULL,fileStdErr,fileStdOut);
                 ^~~~~~
/tmp/scribus20150816-63208-1iq715k/scribus/util_ghostscript.h:42:21: note: candidate function not viable: requires at most 2 arguments, but 4 were provided
int     SCRIBUS_API callGS(const QString& args_in, const QString device="");
                    ^
/tmp/scribus20150816-63208-1iq715k/scribus/util_ghostscript.h:41:21: note: candidate function not viable: requires at most 2 arguments, but 4 were provided
int     SCRIBUS_API callGS(const QStringList& args_in, const QString device="");

**Comment by LiamHD** [comment]
Just tried again. Works fine. Sorry.

**Comment by luzpaz** [comment]
@LiamHD let us know if you have anymore issues getting in the way for you to develop Scribus on OSX
