### ISSUE TITLE
Integrate Travis-CI

### ISSUE THREAD

**Issue by luzpaz** [scribusproject/scribus#3]
_From @luzpaz on August 9, 2014 2:46_

Changelog
- [x] Sign up with [Travis-CI](http://docs.travis-ci.com/user/getting-started/) (free for OSS Projects)
- [x] Ability to trigger Travis CI through any PR or Push
- [x] Write a [.travis.yml](http://docs.travis-ci.com/user/build-configuration/) file ([gist in progress](https://gist.github.com/luzpaz/82ab8a0dad9e4f5520f1))
- [x] Figure out where the .travis.yml file will live (perhaps master branch? if and when Travis CI proves to be a good idea; talk to core-devs about putting it in trunk so it's mirrored to github?)
- [x] [Build result notifications](http://docs.travis-ci.com/user/notifications/) through email, [IRC](http://docs.travis-ci.com/user/notifications/#IRC-notification) and much more
- [x] Multiplatform Builds
   - [x] Linux
     - [x] clang
     - [x] gcc
   - [x] MacOSX (PR https://github.com/scribusproject/scribus/pull/29)
     - [x] clang 
     - ~~gcc~~ (not relevant)
   - [ ] Windows
      * not possible yet (https://github.com/andreas-vox/ScribusCTL/issues/9)

------
Future directionality
* Integrate different tests 
  - [ ] Every so often trigger a [Coverty](https://scan.coverity.com/travis_ci) scan through Travis CI ([travis docs](http://docs.travis-ci.com/user/coverity-scan/))
     * Requires making a separate branch and just initiating every so often. 
        * Request the assistance from @QuLogic 
   * ~~Follow up with bugtracker issues [Automated "black box" test suite](http://bugs.scribus.net/view.php?id=2231)~~
  - [ ] Integrate Regression Testing at some point (https://github.com/scribusproject/scribus/issues/18)
  * Think of how we can tests Scribus via Travis-CI

**Comment by QuLogic** [comment]
I set this up for scribus too, but I'll wait to see what decisions are made on ScribusCTL before opening the PR.

**Comment by luzpaz** [comment]
.travis.yml was merged successfully. 
Lets figure out how to trigger coverty scans now: https://scan.coverity.com/travis_ci

**Comment by luzpaz** [comment]
Nice tip from http://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build
```
Skipping a build #

If you don’t want to run a build for a particular commit, because all you are changing is the README for example, add [ci skip] to the git commit message.

Commits that have [ci skip] anywhere in the commit messages are ignored by Travis CI.
```

**Comment by luzpaz** [comment]
OSX build script now works! What is left is to integrate it with the current linux travis.yml
https://github.com/scribusproject/scribus/pull/29

**Comment by luzpaz** [comment]
Closed https://github.com/andreas-vox/ScribusCTL/issues/2 in favor of this ticket

**Comment by luzpaz** [comment]
Closing ticket as this is functioning. All other additions may or may not be turned in to issues. Most likely they will be mentioned.
