### ISSUE TITLE
How often is this repository synced with SVN

### ISSUE THREAD

**Issue by khaledhosny** [scribusproject/scribus#50]
How often is this repository synced with SVN, is it automated or done manually? I’m asking because we are using this repository to track SVN and there seem to be a bit of lag.

**Comment by luzpaz** [comment]
Manually. Up till this moment I think that I've been the one syncing it using @chhitz script. Is there a necessity for it to happen automatically and more frequently ?

**Comment by khaledhosny** [comment]
It would be nice if it ca run automatically so that we can always be up to date, but I don’t know off hand of a way to do it other than some cron job running somewhere. I think manually should be OK for now, I can adjust my expectations after knowing that.

**Comment by aoloe** [comment]
we have had bad experiences with automated system and, until now, the manual process seems to be good enough...
but we can for sure further improve it!

**Comment by aoloe** [comment]
@khaledhosny, i've added you to the a new team of svn "syncers"...

you can now push to to the scribus repository...  
of course: please, don't do it! (or you'll break the sync mechanism...)

but now you can use the script written by chitz  
https://github.com/scribusproject/scribus_svn_git  
to synchronize the github repository with the svn one.

feel free to ask on irc or here further questions, on how to use the script... or suggest any improvent.

(for now the "distributed" way of syncing seems to be pretty efficient and stable... but feel free to run the script automatically, if you feel a need for it! we just want to be sure that we can trigger it manually, when the automatic way fails... ).
