### ISSUE TITLE
Ever thought of porting Scribus to Eectron?

### ISSUE THREAD

**Issue by mamarilmanson** [scribusproject/scribus#53]
I don't have much detail to say… but it's just a though for now… might reach a larger dev audience… :)

**Comment by luzpaz** [comment]
@mamarilmanson Scribus is not browser based its built with Qt5... what you're suggesting is a total rewrite of Scribus? (or else I'm missing something?)

**Comment by aoloe** [comment]
@mamarilmanson i guess that if you want do such a move, you have to restart a new scribus from scratch.
i'm following a bit the discussions on atom vs. sublime and it seems that electron already has issues with rendering syntax highlightings for big text files... i wonder if it can manage micro-typography and displaying heavy images.
also, html+css -- while making steady progresses -- do not seem to be ready yet for typography work.
but feel free to demonstrate the contrary!

p.s. sadly, i've missed stéphanie's workshop on doing layout with html at this year's lgm :-(
it could have given me some more insights on this topic...

**Comment by mamarilmanson** [comment]
"but feel free to demonstrate the contrary!" - I felt motivated but time is not on my side unfortunately... 

On my subjective suggestion... I feel it will reach out to more devs to contribute as far as the learning curve of the language to be used is concerned (html/css)...

but as far as a design program somehow it felt achievable... I found this one: http://www.pixate.com/ but it is for mobile... I just see potential for a design app with a more familiar backend for me to scroll up and down... :D

**Comment by mamarilmanson** [comment]
and also this one which had a cameo on one talk I saw on youtube: https://github.com/benogle/curve-app

**Comment by mamarilmanson** [comment]
and another one? https://mockingbot.in/?#

**Comment by andreas-vox** [comment]
Hi,

 

I don’t think a port of Scribus to Electron is feasible.. As others already noted, it would be a complete rewrite since the programming language and platform are different.

 

The other apps you linked are toy applications compared with Scribus. It’s kind of like comparing MS Paint to Photoshop…

 

/Andreas

**Comment by luzpaz** [comment]
@mamarilmanson thanks for your input nonetheless
Closing ticket

**Comment by aoloe** [comment]
a few provocative questions:

- why hasn't the curve app developed to an inkscape ersatz in the last 9 months?
- why are all the commits by one single person (what's about the larger dev audience?)
- have you tried to move a group of 1000 shapes in curve.app?


personally, i also believe that a higher level language would help having more developers, but i'm not sure that a full rewrite is doable.

at the end, a few dedicated programmers -- or even just one! ... like in the case of curve--  seem to lead to better results than waiting for the big crew to join...

**Comment by mamarilmanson** [comment]
:+1: 

:D

**Comment by andreas-vox** [comment]
A higher level language than C++? That would not be JavaScript then, but rather something like OCaml, Prolog or Haskell. And good luck with finding developers for that…

 

I think refactoring the C++ source into something more structured is a better approach, and a clean scripting interface could open the way to alternate GUIs.

 

Just my €0.02.

 

/Andreas
