### ISSUE TITLE
"Dialogless" user experience

### ISSUE THREAD

**Issue by aberba** [scribusproject/scribus#56]
Using scribus now is vey difficult and time consuming because of the dialog which don't offer instant preview.  Why don't devs get rid of that feature? 

Instead, text boxes could have inline editting.

**Comment by aoloe** [comment]
hi @laberba, have you tried double clicking on a text frame? :-)

**Comment by laberba** [comment]
Nope. I was using 1.x by the way.

**Comment by aoloe** [comment]
in 1.4 you can double click a text frame and edit your text inline.

**Comment by laberba** [comment]
What about in-line styling? Thats the main issue here

**Comment by aoloe** [comment]
i don't know what exactly you mean by in-line styling, but i can guess what it could be...

in my eyes the solution for efficient style applying is to allow a shortcut that popups an inline style list with live filter that applies the style on return...

**Comment by laberba** [comment]
+1 like Microsoft word. Works really well.

**Comment by luzpaz** [comment]
Closing. Please open a feature ticket on the main Scribus bugtracker: http://bugs.scribus.net
