### ISSUE TITLE
Arabic "Align Text Forced Justified" single word wrongly justified to the left

### ISSUE THREAD

**Issue by munzirtaha** [scribusproject/scribus#65]
"Align Text Forced Justified" wrongly aligns a single word to the left where as it should be aligned to the right. Attached is a screenshot.
![scribus-arabic-force-justified](https://cloud.githubusercontent.com/assets/2936425/20911269/ef15a616-bb77-11e6-99cb-2442eb45eef3.png)

**Comment by munzirtaha** [comment]
Should I file this upstream too?

**Comment by Fahad-Alsaidi** [comment]
Yes please

**Comment by munzirtaha** [comment]
done!
https://bugs.scribus.net/view.php?id=14445

**Comment by luzpaz** [comment]
should be fixed in 376b6973f2cbcfaaf1e7b1788f3f772808c3c21c

**Comment by munzirtaha** [comment]
Thanks!

**Comment by luzpaz** [comment]
fix pt.2 in a8bbdec89ed200a39b7c7e173ea8ffc16a7220fb
