### ISSUE TITLE
Travis build should do make install

### ISSUE THREAD

**Issue by khaledhosny** [scribusproject/scribus#67]
It seems that make install is often broken (missing to add files, or remove dropped files from cmake mostly), so I think Travis build better try to catch that.

**Comment by luzpaz** [comment]
@khaledhosny thanks for the suggestion. I'll make a patch for craig to merge

**Comment by luzpaz** [comment]
travis complains of needing admin privileges. I need to read up on using sudo and what that entails.. IIRC there were some hoops to jump through using it.

**Comment by khaledhosny** [comment]
You can use `CMAKE_INSTALL_PREFIX` to install to a user-writable directory (e.g. `~/.local`).

**Comment by luzpaz** [comment]
patched in r21655 
Thanks Khaled. Closing

**Comment by luzpaz** [comment]
@khaledhosny adding make install to OSX builds makes it fail due to:
```The job exceeded the maximum time limit for jobs, and has been terminated.```
https://travis-ci.org/scribusproject/scribus/jobs/184663349#L4808

is there a way to optimize the OSX build or should I just remove the `make install` from it?

**Comment by khaledhosny** [comment]
I have no idea, that build does not seem to have finished make so don’t see how make install is involved.

**Comment by Fahad-Alsaidi** [comment]
There is a option to tell travis to wait till the task finish.

**Comment by luzpaz** [comment]
oh you're right. I erroneously thought it exceeded time threshold while it was in make install

**Comment by luzpaz** [comment]
added in 2376f1762a66e53a7ccb27506dd8a5c499415b2b
