### ISSUE TITLE
OpenType is a single word

### ISSUE THREAD

**Issue by khaledhosny** [scribusproject/scribus#69]
I see few places where it is written “Open Type” with a space (`git grep "Open Type"`), it should be changed to “OpenType” or just dropped (e.g. “Font Features” is enough, no need for OpenType here).

**Comment by luzpaz** [comment]
The only result I see is: 
```ui/propertiespalette_text.cpp:  fontfeaturesWidgetItem = textTree->addItem(fontfeaturesWidget, tr("Open Type Font Features"));```

**Comment by luzpaz** [comment]
Craig decided to keep it as "OpenType" in fb146c1ee945f231fc6efdd08419140b2de6c3f0
Thanks khaled. 
Closing

**Comment by khaledhosny** [comment]
The features should work with Graphite fonts and AAT fonts (if HarfBuzz is built with them), so calling it OpenType features is misleading. Sure they don’t work with Type 1 fonts, but these fonts don’t have any features anyway so there is not much confusion (and they should be all disabled for such fonts).

**Comment by JLuc** [comment]
later renamed to plain "Font features" in https://www.scribus.net/websvn/comp.php?repname=Scribus&compare[]=%2F@21800&compare[]=%2F@21801
