### ISSUE TITLE
Integrate Transifex (Continuous Translation)

### ISSUE THREAD

**Issue by luzpaz** [scribusproject/scribus#7]
_From @luzpaz on September 12, 2014 23:15_
Edit: Updated June 16, 2015 

Needs
--------
- [x] A person familiar with Transifex to help with the learning curve of implementation ~~(@kovidgoyal of the famed [calibre project](https://github.com/kovidgoyal/calibre)) has offered to answer questions we have)~~ Thanks to previous helpers but solutions were not streamlined. @chhitz has offered his kind assistance 
  * - [x] Download the [transifex command line client tx](http://docs.transifex.com/developer/client/setup)  
  * - [x] Create a separate github project ~~to commit all the .pot/.po files to it, so even if something goes wrong in transifex, you can always recover. See for example: [calibre-translations](https://github.com/kovidgoyal/calibre-translations)~~ Not sure this will be utilized after all

             ~~Commit .pot/.po files to newly created [scribus/scribus-translations](https://github.com/scribusproject/scribus-translations/) repo~~ not relevant anymore
  * - [ ] Study and setup up workflow ~~'How to manage Translations' in scribus using https://github.com/scribusproject/scribus/issues/14#issuecomment-55691582 and https://github.com/scribusproject/scribus/issues/14#issuecomment-55693950~~  
     * - [ ] ~~Make a Scribus verion of Calibre's [setup/translations.py](https://github.com/kovidgoyal/calibre/blob/master/setup/translations.py)~~  
     * - [ ] ~~Modify [class POT](https://github.com/kovidgoyal/calibre/blob/master/setup/translations.py#L25) **gets all translateable strings from the calibre source code and user manual and uploads the .pot files to transifex using tx**~~
     * - [ ] ~~Modify [class Translations](https://github.com/kovidgoyal/calibre/blob/master/setup/translations.py#L191) **compiles them to .mo format for distribution using msgfmt**~~
     * - [ ] ~~Modify [class GetTranslations](https://github.com/kovidgoyal/calibre/blob/master/setup/translations.py#L353)  **downloads translations from transifex, checks them using pofilter and uploads them to GitHub.**~~
     * - [ ] ~~Figure out how to trigger automation ("*These commands are run once a week automatically as part of calibre's release process, so that everything is kept up to date.*" **Maybe add them to part of mrscribe's script triggered weekly/bi-weekly and/or the option to  trigger manually via the bot on IRC?** ask @moskalenko~~ 

Questions:  
* - [ ] The majority of the Translation files are *.ts How does this impact workflow ?
* - [ ] Right now the Scribus transifex URL is https://www.transifex.com/projects/p/Scribus_140/ reflecting Scribus v1.4 Should we change this to a more generic URL since it's the source files that indicates the version? If for each version we need to change the URL and thus most likely breaking that link it's not an intelligent idea. 
* - [ ] Right now there are 2 older source files on Transifex. What happens to them when I upload the 1.5 source file version?
* - [ ] there is a request on Transifex to add French. French is an already translated language. If a new language it is generated from the main (english) source file. Do I then upload the current french source file to that Transifex translation group. 
* - [ ] How to merge the translations that live in Transifex already and current translation committed to Scribus SVN branch
* - [ ] How to avoid well known mistakes (avoid losing translations during source file updates)

Other Todos
- [ ] Volunteers to manage and maintain Transifex
- [ ] Workflow tutorials for maintainers
- [ ] Get the official scribus translators and the Transifex translators acquainted with each other and as many translators on Transifex. 
- [ ] Talk to translators about guidelines on how to contribute translations

Translations issues:  
- [ ] Figure out a protocol for scribus-assigned keyboard shortcuts

Reference URLs
----------------------
* Transifex [translation jargon](http://docs.transifex.com/developer/formats/)
* [Transifex](http://bugs.scribus.net/view.php?id=10589) in Scribus issue queue
* [Scribus in Transifex](https://www.transifex.com/projects/p/Scribus_140/)
* Scribus translation files (SVN branch) https://github.com/scribusproject/scribus/tree/svn/resources/translations
* Scribus [translators](https://github.com/scribusproject/scribus/blob/svn/TRANSLATION)

_Copied from original issue: scribusproject/scribus-old-to-be-deleted#14_

**Comment by luzpaz** [comment]
Some thoughts:
So what happens when a new translation source file is uploaded ? What happens to old translations:
If one chooses to [automatically update the source file](http://docs.transifex.com/faq/#update-source-files-automatically): 
* New strings will be added.
* Modified strings will be considered as new ones and added as well.
* Strings, which do not exist in the new source file (including ones which have been modified), will be removed along with their translations.

*However, old translations are kept in the [Translation Memory](http://docs.transifex.com/guides/localization#translation-memory-tm) of the project.*

**Comment by luzpaz** [comment]
_From @kovidgoyal on September 16, 2014 3:47_

Just a few tips:

1) Use the transifex command line client tx
2) Create a separate github project and commit all the .pot/.po files to it, so even if something goes wrong in transifex, you can always recover. See for example: https://github.com/kovidgoyal/calibre-translations
3) If you wish to learn how I manage translations in calibre, see the file setup/translations.py
The class POT gets all translateable strings from the calibre source code and user manual and uploads the .pot files to transifex using tx
The class Translations compiles them to .mo format for distribution using msgfmt
The class GetTranslations downloads translations from transifex, checks them using pofilter and uploads them to GitHub.
These commands are run once a week automatically as part of calibre's release process, so that everything is kept up to date.

**Comment by luzpaz** [comment]
@kovidgoyal sweet!  
Thank you very much. Will study your tips. 
Reference notes:  
* Calibre's [setup/translations.py](https://github.com/kovidgoyal/calibre/blob/master/setup/translations.py)  
  * [class POT](https://github.com/kovidgoyal/calibre/blob/master/setup/translations.py#L25) **gets all translateable strings from the calibre source code and user manual and uploads the .pot files to transifex using tx**
  * [class Translations](https://github.com/kovidgoyal/calibre/blob/master/setup/translations.py#L191) **compiles them to .mo format for distribution using msgfmt**
  * [class GetTranslations](https://github.com/kovidgoyal/calibre/blob/master/setup/translations.py#L353)  **downloads translations from transifex, checks them using pofilter and uploads them to GitHub.**

**Comment by gyuris** [comment]
Bingo! Transifex would be great for Scribus! I use it in other projects. I'm the Hungarian translator. If you need a tester, I can help.

**Comment by luzpaz** [comment]
@gyuris would you like to help implement this? or know anyone who'd be interested ?

**Comment by gyuris** [comment]
@luzpaz Sorry, I'm not a developer :(

**Comment by luzpaz** [comment]
@chhitz based on our previous conversation lets update the ticket here 

@gyuris no probs. I'll check in with you when we get Transifex up and running and we can then take you up on testing it. Thanks!

**Comment by luzpaz** [comment]
Some concerns were brought up on the channel the other day:
See http://irclogs.scribus.net/%23scribus/2015/2015-05/%23scribus.2015-05-25.log

**Comment by luzpaz** [comment]
musescore FTW: 
https://musescore.org/node/22982 and @anomaly404 who spearheaded the project
@chhitz maybe we can do something like this. Craig has a resource manager in Scribus though not yet enabled.

**Comment by luzpaz** [comment]
http://irclogs.scribus.net/%23scribus/2015/2015-05/%23scribus.2015-05-28.log
@chhitz gets greenlight

**Comment by luzpaz** [comment]
@gyuris Check out https://www.transifex.com/projects/p/scribus-14x/language/hu/

**Comment by gyuris** [comment]
:-). 
Why exists Scribus and Scribus 1.4 project? For project structure see my other project on Transifex: https://www.transifex.com/projects/p/openlp/language/hu/

**Comment by luzpaz** [comment]
Scribus 1.4 is stable
"Scribus" I believe is 1.5.1 
Right @chhitz ?

**Comment by aoloe** [comment]
i guess that scribus should be trunk...

**Comment by gyuris** [comment]
1. I suggest to unite trunk and 1.4 or 1.5 projects in Transifex. Why? In Transifex every project has own language team and I must ask permission for every project to translate. This is not ideal for translators and translation teams if there are more projects for Scribus. Please, see the OpenP project structure: there is only one project and there are more branches in this project, there are closed and opened branches... https://www.transifex.com/projects/p/openlp/language/hu/
2. Can you see my ("bubu") permission request in "Scribus 1.4.x" project for Hungarian language team? Please approve me.

**Comment by luzpaz** [comment]
@gyuris thanks for that feedback. Need to get clearer on the the workflow of how translations will be handled now through transifex. A [patch](http://bugs.scribus.net/view.php?id=13097) was submitted by @chhitz to get this ball rolling.

**Comment by luzpaz** [comment]
Closing this issue in favor of https://github.com/scribusproject/scribus/issues/15
