### ISSUE TITLE
Scribus 1.5.2 doesn’t build with Qt 5.8

### ISSUE THREAD

**Issue by ArchangeGabriel** [scribusproject/scribus#82]
I was trying to build Scribus 1.5.2 but it failed with this error:
```
/tmp/scribus-devel/src/scribus-1.5.2/scribus/plugins/gettext/xtgim/xtgscanner.cpp: Dans la fonction membre « void XtgScanner::xtgParse() »:
/tmp/scribus-devel/src/scribus-1.5.2/scribus/plugins/gettext/xtgim/xtgscanner.cpp:1520:21: erreur : ambiguous overload for « operator!= » (operand types are « QChar » and « char »)
  while (lookAhead() != '\0')
         ~~~~~~~~~~~~^~~~~~~
In file included from /usr/include/qt/QtCore/QString:1:0,
                 from /tmp/scribus-devel/src/scribus-1.5.2/scribus/styles/../style.h:21,
                 from /tmp/scribus-devel/src/scribus-1.5.2/scribus/styles/style.h:6,
                 from /tmp/scribus-devel/src/scribus-1.5.2/scribus/styles/charstyle.h:20,
                 from /tmp/scribus-devel/src/scribus-1.5.2/scribus/plugins/gettext/xtgim/xtgscanner.h:31,
                 from /tmp/scribus-devel/src/scribus-1.5.2/scribus/plugins/gettext/xtgim/xtgscanner.cpp:27:
/usr/include/qt/QtCore/qstring.h:1639:13: note : candidate: bool operator!=(QChar, const QStringRef&)
 inline bool operator!=(QChar lhs, const QStringRef &rhs) Q_DECL_NOTHROW { return !(lhs == rhs); }
             ^~~~~~~~
/usr/include/qt/QtCore/qstring.h:1625:13: note : candidate: bool operator!=(const QString&, QChar)
 inline bool operator!=(const QString &lhs, QChar rhs) Q_DECL_NOTHROW { return !(rhs == lhs); }
             ^~~~~~~~
/usr/include/qt/QtCore/qstring.h:1620:13: note : candidate: bool operator!=(QChar, const QString&)
 inline bool operator!=(QChar lhs, const QString &rhs) Q_DECL_NOTHROW { return !(lhs == rhs); }
             ^~~~~~~~
/usr/include/qt/QtCore/qstring.h:1567:13: note : candidate: bool operator!=(const QString&, const QStringRef&)
 inline bool operator!=(const QString &lhs, const QStringRef &rhs) Q_DECL_NOTHROW { return lhs.compare(rhs) != 0; }
             ^~~~~~~~
In file included from /usr/include/qt/QtCore/qstring.h:48:0,
                 from /usr/include/qt/QtCore/QString:1,
                 from /tmp/scribus-devel/src/scribus-1.5.2/scribus/styles/../style.h:21,
                 from /tmp/scribus-devel/src/scribus-1.5.2/scribus/styles/style.h:6,
                 from /tmp/scribus-devel/src/scribus-1.5.2/scribus/styles/charstyle.h:20,
                 from /tmp/scribus-devel/src/scribus-1.5.2/scribus/plugins/gettext/xtgim/xtgscanner.h:31,
                 from /tmp/scribus-devel/src/scribus-1.5.2/scribus/plugins/gettext/xtgim/xtgscanner.cpp:27:
/usr/include/qt/QtCore/qchar.h:576:30: note : candidate: constexpr bool operator!=(QChar, QChar)
 Q_DECL_CONSTEXPR inline bool operator!=(QChar c1, QChar c2) Q_DECL_NOTHROW { return !operator==(c1, c2); }
                              ^~~~~~~~
make[2]: *** [scribus/plugins/gettext/xtgim/CMakeFiles/xtgimplugin.dir/build.make:85: scribus/plugins/gettext/xtgim/CMakeFiles/xtgimplugin.dir/xtgscanner.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3667: scribus/plugins/gettext/xtgim/CMakeFiles/xtgimplugin.dir/all] Error 2
```

Not sure how hard it would be to fix this and at which point backporting to 1.5.2 could be done, but if a simple patch could be provided for 1.5.2 to be built against Qt that would be awesome.

**Comment by aoloe** [comment]
hi

On 08/02/17 23:05, Bruno Pagani wrote:
> I was trying to build Scribus 1.5.2 but it failed with this error:

why are you trying to build 1.5.2?

the issue you're facing is that -- until last week -- scribus was not 
compatible with Qt 5.8.

the patch is simple:

https://github.com/HOST-Oman/scribus/commit/934f651e1e1c769d1561075770885fbaf6a9af21

but the question remains: why don't you compile the current development 
code? (from svn or the github mirror...)

ciao
a.l.e

**Comment by ArchangeGabriel** [comment]
I’m using Scribus only for one project, for which the .sla file is shared amongst all the people involved in. Because we had incompatibilities with different people using different versions, we needed to agree on the same Scribus version. We could have decided on a particular commit, sure, but this is quite unpractical. Also, building Scribus not being an option for some, so we went with what was the latest common denominator, which is the latest development candidate (https://www.scribus.net/downloads/unstable-branch/), 1.5.2.

**Comment by aoloe** [comment]
then:

- patch scribus as mentioned above or
- get a binary released 1.5.2
- install qt 5.7

the simplest thing is probably to patch the scribus code your got.

**Comment by ArchangeGabriel** [comment]
Yes, that’s what I did (patching). Just forgot to close this issue and thank you for the patch, which was indeed quite simple. :)

P.S.: There is a whole bunch of `warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]`, but I suppose you know about them/they’re fixed in current code. ;)

**Comment by aoloe** [comment]
iirc those warnings are in a library that is included in scribus...
