### ISSUE TITLE
Scribus 1.5.3 related questions/issues

### ISSUE THREAD

**Issue by ArchangeGabriel** [scribusproject/scribus#89]
Hi there,

I’ve seen the recent release of Scribus 1.5.3. :)

One question first: I’ve seen the PGP key has changed from the one of Peter Linnell to one for the Scribus Team, but can’t find any info on scribus.net about this. Also, this new key is not signed by Peter Linnell one. Is that normal?

One (and a half) comment then: the documentation (wrong link here https://www.scribus.net/scribus-1-5-3-released/ but I guessed https://wiki.scribus.net/canvas/1.5.3_Release) says harfbuzz and icu are now needed, but it should be more precise I think and tell that harfbuzz-icu is required (this is a different package and generally depends on the previous two btw). ;)

One problem finally: when building, PoDoFo detection fails but I’m not sure why. Is that an issue on Scribus side or on my distro side?
```
CMake Warning at cmake/modules/FindLIBPODOFO.cmake:48 (find_package):
  By not providing "FindOPENSSL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OPENSSL", but
  CMake did not find one.

  Could not find a package configuration file provided by "OPENSSL" with any
  of the following names:

    OPENSSLConfig.cmake
    openssl-config.cmake

  Add the installation prefix of "OPENSSL" to CMAKE_PREFIX_PATH or set
  "OPENSSL_DIR" to a directory containing one of the above files.  If
  "OPENSSL" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:848 (find_package)


OpenSSL NOT found for installed version of PoDoFo (>= 0.9.5) - Disabling support for PDF embedded in AI
PoDoFo NOT found - Disabling support for PDF embedded in AI
```

Thanks!

**Comment by aoloe** [comment]
hi archange gabriel,

- as far as i know, the main part is the SHA checksum, which is in the release notes in the wiki.
- no idea if a PGP verification has been made public in the past... but, yes, it would be nice to have some more information on that...
- the link with the dashes is an article on the site, the other one are the release notes in the wiki...
- concerning the dependency on harfbuzz-icu: you could be right there... i've [added a ticket](https://github.com/scribusproject/scribus/issues/89)
- concerning podofo, you might have a version older than 0.9.5?

**Comment by gyuris** [comment]
Correct link is about harfbuzz-icu: https://bugs.scribus.net/view.php?id=14828

**Comment by gyuris** [comment]
Correct ticket link about harfbuzz-icu: https://bugs.scribus.net/view.php?id=14828

**Comment by aoloe** [comment]
thanks @gyuris ! i've fixed the link now...

**Comment by ArchangeGabriel** [comment]
>as far as i know, the main part is the SHA checksum, which is in the release notes in the wiki.
>no idea if a PGP verification has been made public in the past... but, yes, it would be nice to have some more information on that...

They are .asc files at https://sourceforge.net/projects/scribus/files/scribus-devel/1.5.3/. For 1.5.2 at least, those were made with Peter Linnell key (). But for 1.5.3, it’s “The Scribus Team” key ().
>the link with the dashes is an article on the site, the other one are the release notes in the wiki...

I was saying that the link on this page https://www.scribus.net/scribus-1-5-3-released/ was erroneously pointing to https://wiki.scribus.net/canvas/1.5.2_Release, but that I had guessed the correct one to be https://wiki.scribus.net/canvas/1.5.3_Release. But this has been corrected now. 

However, links at https://www.scribus.net/downloads/unstable-branch/ are wrong too: `http://sourceforge.net/projects/scribus/files/scribus-devel/1.5.3/` is displayed but they point to `http://sourceforge.net/projects/scribus/files/scribus-devel/1.5.2/`.

>concerning the dependency on harfbuzz-icu: you could be right there... i've added a ticket

OK, thanks.

>concerning podofo, you might have a version older than 0.9.5?

No, I have 0.9.5. It seems more to be an issue with OpenSSL version (we have both 1.0 and 1.1 on ArchLinux, my distro). But I’m not sure why it’s triggered here, podofo depends on openssl but scribus does not AFAIK, does it?

**Comment by aoloe** [comment]
- i've reported the wrong links on https://www.scribus.net/downloads/unstable-branch/
- i don't think that scribus depends directly on openssl... so your error seems to be rather related to podofo...

**Comment by ArchangeGabriel** [comment]
Hum… I’ve found this commit: https://github.com/scribusproject/scribus/commit/7fea6ab936e744b03f6119cdf492523d4f7112c1

Likely the culprit. Question is: is that expected to not find OpenSSL while it’s here? What did you add this check? If I have PoDoFo on my system, it likely means that the corresponding OpenSSL libs needed are here to, isn’t it?

**Comment by aoloe** [comment]
while i agree with you that scribus should not check if openssl is installed (since at least in debian it is a hard dependency), scribus can be compiled on multiple OSes and i wonder if there are any where libpodofo can be installed without ssl...

if you think something is wrong there, please fill a ticket on https://bugs.scribus.net and you'll get an answer or the issue patched...

**Comment by ArchangeGabriel** [comment]
Well, I think Scribus should not check anything related to OpenSSL, because either it’s an hard dependency for PoDoFo and will be installed anyway or it’s not and hard dependency for PoDoFo and then I don’t see why it would matter for Scribus that OpenSSL is installed or not if PoDoFo doesn’t need it.

I’d like to avoid opening yet another account just to open a ticket on bugs.scribus.net.

**Comment by aoloe** [comment]
don't worry, you'll get addicted and submit lot of tickets to the main bug tracker : - )

**Comment by aoloe** [comment]
i don't know, there might be OSes where podofo might not depend on openssl (because it's hard to get to work there) but scribus relies on it so it has to check specifically on openssl being there (i think of something like OS2 or Haiku...)

i'll ask the question for you in the bug tracker... for this time :-)

**Comment by aoloe** [comment]
just one question: can you compile (and import PDFs) if you remove those lines from the `CMakeLists.txt` file?

**Comment by ArchangeGabriel** [comment]
Thank you! Truth is I only used Scribus for my school newspaper, and I just kept over the package in Arch from this time, but I don’t really use it anymore. So unless Scribus fails again at building during the next year (ETA before I leave the package to someone else because I won’t be knowing anyone in the school newspaper team by this time, especially using Arch), it’s unlikely I open new bugs.

I can export to PDF even with those lines (by the error message I guess only importing should be broken, I guess it this since I have no PDF import option in the menus). I’ll try building without the lines and see what it gives. Keep you updated soon.

**Comment by aoloe** [comment]
yes, libpodofo is used for the pdf import, not the export.

**Comment by ArchangeGabriel** [comment]
So without this line it works OK.

**Comment by aoloe** [comment]
submitted https://bugs.scribus.net/view.php?id=14838

**Comment by aoloe** [comment]
the check seems to be needed... see the comment in the bug report.

**Comment by ArchangeGabriel** [comment]
OK… But then figuring this issue about OpenSSL detection is necessary. I do have an `FindOpenSSL.cmake` at `/usr/share/cmake-3.8/Modules/`, but adding it to CMAKE_MODULE_PATH does not change anything.

**Comment by aoloe** [comment]
the debian maintainer seems to have found where the issue is:

https://bugs.scribus.net/view.php?id=14850

i'll sync the github repository over lunch and you'll be able to get the fixed configuration! (hopefully...)

**Comment by aoloe** [comment]
p.s.: can you confirm if the patch solves the issue for you?

**Comment by ArchangeGabriel** [comment]
Thanks, it indeed fixes it. ;) So only remaining question is about PGP. Is there an IRC somewhere I can ask maybe?

**Comment by aoloe** [comment]
yes, we're on freenode...
craig (mrb) already confirmed to the (same) debian maintainer that the team did sign the upload.

now, my question is: where and how should the PGP info be published?

**Comment by ArchangeGabriel** [comment]
I guess download pages are the best place for this: https://www.scribus.net/downloads/stable-branch and https://www.scribus.net/downloads/unstable-branch.

**Comment by ArchangeGabriel** [comment]
And regarding how, I would say something in the lines of:
“Our sources and MacOS releases are signed using PGP. The key use for this is <fingerprint or link to the key on a keyserver>. Signature for each release file is available at the same location with the supplemental .asc extension.”

If you ever start signing Windows’ .exe (but I guess they are signed using MS embedded signature framework or what ever this is called), you could remove ”sources and MacOS” from the first sentence.

**Comment by plinnell** [comment]
https://bugs.scribus.net/view.php?id=14838 fixes the issue
