### ISSUE TITLE
Could you make it integrate into the system?

### ISSUE THREAD

**Issue by Lvaskz** [scribusproject/scribus#91]
Hi, this is more a request than a problem, although perhaps for some people it is.
Appimage is not integrated into the linuxmint system 18.2. In some appimages at the time of making the application executable, the application asked if you would like integrate it into the system, but I see that it does not happen now. Nor the official version of krita. Could you make it possible in any way?
When you have many appimage not integrated in the system, it gets some tedious fill the desktop with shortcuts
thanks

**Comment by aoloe** [comment]
hi @Lvaskz , i think that you should make this request in the appimage project...

generally speaking, the appimage is mostly maintained by people outside of the scribus team... so: feel free to make contributions!
