### ISSUE TITLE
"Scribus crashes due to Signal #11" if I try to insert a linebreak

### ISSUE THREAD

**Issue by kannes** [scribusproject/scribus#92]
Scribus 22163-1 built from SVN some hours ago on up-to-date Archlinux.

Scribus crashes if I try to add a linebreak to this file: [crashes if i try to add a line.sla.zip](https://github.com/scribusproject/scribus/files/1324537/crashes.if.i.try.to.add.a.line.sla.zip)

Doubleclick into the text-frame, so that the cursor is at the end of the "Ta" line, then hit Enter. "Scribus crashes due to Signal #11".

A backtrace:

$ gdb --args scribus file.sla 
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from scribus...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/scribus file.sla
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe31af700 (LWP 7992)]
[New Thread 0x7fffd8b78700 (LWP 7993)]
[New Thread 0x7fffd3fff700 (LWP 7994)]
[New Thread 0x7fffd37fe700 (LWP 7995)]
[New Thread 0x7fffd2dbb700 (LWP 7996)]
FFmpegImageStream::open : av_open_input_file() failed : AVERROR_NOENT
ReaderWriterTF::writeObject
Warning: dynamic library '/usr/lib/osgPlugins-3.4.1/osgdb_xine.so' exists, but an error occurred while trying to open it:
/usr/lib/osgPlugins-3.4.1/osgdb_xine.so: undefined symbol: xine_xmalloc_aligned
sizeof(TrkHeader)=1000
setBestEncoding for  MyriadPro-Bold  with  848 glyphs, hasNames= 512 , POST size= 32
Checking cmap  0 ( 0 , 3 , 0 ) format  4
found Unicode enc for Myriad Pro Bold as map 0 with 835 glyphs
Checking cmap  1 ( 1 , 0 , 0 ) format  6
Checking cmap  2 ( 3 , 1 , 0 ) format  4
found Unicode enc for Myriad Pro Bold as map 2 with 1670 glyphs
Checking cmap  3 ( 7 , 0 , 0 ) format  -1
using Unicode enc for Myriad Pro Bold
setBestEncoding for  MyriadPro-Regular  with  848 glyphs, hasNames= 512 , POST size= 32
Checking cmap  0 ( 0 , 3 , 0 ) format  4
found Unicode enc for Myriad Pro Regular as map 0 with 835 glyphs
Checking cmap  1 ( 1 , 0 , 0 ) format  6
Checking cmap  2 ( 3 , 1 , 0 ) format  4
found Unicode enc for Myriad Pro Regular as map 2 with 1670 glyphs
Checking cmap  3 ( 7 , 0 , 0 ) format  -1
using Unicode enc for Myriad Pro Regular
setBestEncoding for  ArialMT  with  1320 glyphs, hasNames= 512 , POST size= 12804
Checking cmap  0 ( 0 , 3 , 0 ) format  4
found Unicode enc for Arial Regular as map 0 with 1186 glyphs
Checking cmap  1 ( 1 , 0 , 0 ) format  0
Checking cmap  2 ( 3 , 1 , 0 ) format  4
found Unicode enc for Arial Regular as map 2 with 2372 glyphs
using Unicode enc for Arial Regular
QPixmap::scaled: Pixmap is a null pixmap
QPainter::begin: Paint device returned engine == 0, type: 2
QPixmap::scaled: Pixmap is a null pixmap
QPainter::end: Painter not active, aborted

Thread 1 "scribus" received signal SIGSEGV, Segmentation fault.
0x00007fffef98057e in QTextCodec::fromUnicode(QString const&) const () from /usr/lib/libQt5Core.so.5
(gdb) bt
#0  0x00007fffef98057e in QTextCodec::fromUnicode(QString const&) const () at /usr/lib/libQt5Core.so.5
#1  0x0000555555a45a8b in Hyphenator::slotHyphenateWord(PageItem*, QString const&, int) ()
#2  0x0000555555b32214 in PageItem_TextFrame::handleModeEditKey(QKeyEvent*, bool&) ()
#3  0x000055555598e040 in CanvasMode_Edit::keyPressEvent(QKeyEvent*) ()
#4  0x0000555555e0b53f in ScribusView::eventFilter(QObject*, QEvent*) ()
#5  0x00007fffef91f89c in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff0646e28 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff064feb3 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#8  0x00007fffef91fbd0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#9  0x00007ffff06a667c in  () at /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff0646e4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff064e926 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#12 0x00007fffef91fbd0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#13 0x00007fffefe7ecb2 in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () at /usr/lib/libQt5Gui.so.5
#14 0x00007fffefe83d26 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#15 0x00007fffefe5b4ac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#16 0x00007fffe5389cc1 in  () at /usr/lib/libQt5XcbQpa.so.5
#17 0x00007fffeae6ba57 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#18 0x00007fffeae6bc88 in  () at /usr/lib/libglib-2.0.so.0
#19 0x00007fffeae6bd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#20 0x00007fffef97a061 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#21 0x00007fffef91dffb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#22 0x00007fffef927048 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#23 0x00005555562692d5 in mainApp(int, char**) ()
#24 0x00007fffeea0ff6a in __libc_start_main () at /usr/lib/libc.so.6
#25 0x000055555587be7a in _start ()

**Comment by aoloe** [comment]
reported as https://bugs.scribus.net/view.php?id=14999

**Comment by aoloe** [comment]
solved

see the comments in the scribus bug tracker.
