### ISSUE TITLE
Edit Image > Gimp

### ISSUE THREAD

**Issue by wstaelens** [scribusproject/scribus#93]
when doing right mouse click on Image > "Edit Image..." I get the message: "The program gimp is missing!"
...but Gimp is installed... 

I'm using both x64 versions of Scribus and Gimp (GIMP 2.8.22):
C:\Program Files\Scribus 1.4.6
C:\Program Files\GIMP 2

Windows 10 Pro x64 FallCreators update.

![gimp scribus](https://user-images.githubusercontent.com/7447285/32549784-fed738fe-c48a-11e7-8c64-475193b46c83.PNG)

**Comment by aoloe** [comment]
this is not an issue... this is a support question.

can i ask you to please fill it in http://forums.scribus.net ?

**Comment by wstaelens** [comment]
to me this sounds as an issue.
Gimp is installed.
Scribus is installed.

I do "Edit image" and it tells me that gimp is missing.
So must be that Scribus doesn't automatically search in the correct default locations... (assuming that it does an auto search attempt first).

(and to be honest, I'm not creating yet another account...)

**Comment by aoloe** [comment]
sorry, for the delay.
scribus does probably not try too hard when searching on windws.
you have to set he path in the preferences, if it does not work for you.

i have not used much windows for several years, but every time i have to sort something out, the path management seams to be a mess.
if you know that it's now fine and know how to fix that, please provide a patch that lets scribus correctly search for gimp.

**Comment by patreg** [comment]
I am using Gimp2 in Windows 10 and was editing my brochure using Scribus 1.4.7.  Here's the solution:

In Scribus, Go to File --> Preferences --> External Tools. Find Image Processing Tool, change the entry by clicking the menu "Change..." from "gimp" or whatever is there to C:\Program Files\GIMP 2\bin\gimp-2.8.exe. Apply and click OK. Scribus should link with Gimp2.

I hope this helps.

**Comment by aoloe** [comment]
closing this, since it's not really a scribus issue...

**Comment by Etxebarri** [comment]
> I am using Gimp2 in Windows 10 and was editing my brochure using Scribus 1.4.7. Here's the solution:
> 
> In Scribus, Go to File --> Preferences --> External Tools. Find Image Processing Tool, change the entry by clicking the menu "Change..." from "gimp" or whatever is there to C:\Program Files\GIMP 2\bin\gimp-2.8.exe. Apply and click OK. Scribus should link with Gimp2.
> 
> I hope this helps.

Thank you very much. I had been having problems getting Gimp to work with Scribus as I was getting the same message "Gimp missing", but after following your advice it finally worked. Merci!
