### ISSUE TITLE
Scribus 1.5.4 has a bad GPG signature

### ISSUE THREAD

**Issue by ArchangeGabriel** [scribusproject/scribus#97]
After downloading `scribus-1.5.4.tar.xz{,.asc}`:
```
$ gpg --verify scribus-1.5.4.tar.xz.asc
gpg: assuming signed data in 'scribus-1.5.4.tar.xz'
gpg: Signature made Sat Apr 28 01:45:42 2018 CEST
gpg:                using DSA key 0xEF7B95E7F60166DA
gpg: BAD signature from "Peter Linnell <plinnell@scribus.net>" [unknown]
```

**Comment by plinnell** [comment]
I've uploaded a new signature  on Sourceforge. Thanks for reporting, but it should have gone to https://bugs.scribus.net

**Comment by ArchangeGabriel** [comment]
Sorry, I try to avoid creating new accounts everywhere when I can. But thanks for the quick fix!

**Comment by ArchangeGabriel** [comment]
Question: If you really want people to report at bugs.scribus.net, why is there an “Issues” section here?

**Comment by ArchangeGabriel** [comment]
I agree with you.

And well, ideally I would just never open tickets. ;) But since the one I opened right now would have been the fourth one, I moved to the official bug tracker for it.
